export const products = [
    {name: 'Johnson\'s Tear Free Gentle Baby Shampoo, Free of Parabens, Phthalates, Sulfates and Dyes, 6.8 fl. oz',
UPC: '0381371175017',
imageURL: 'https://www.johnsonsbaby.com/sites/jbaby_us_3/files/styles/jjbos_adaptive_images_generic-tablet/public/product-images/jns_381371175024_600ml_00000_1000wx1000h.jpeg',
ingredients: 'Water, Cocamidopropyl Betaine, Decyl Glucoside, Sodium Cocoyl Isethionate, Lauryl Glucoside, PEG-80 Sorbitan Laurate, Glycerin, Citric Acid, Sodium Benzoate, PEG-150 Distearate, Sodium Methyl Cocoyl Taurate, Fragrance, Polyquaternium-10, Disodium EDTA'},
{name: 'Cetaphil Baby Gentle Wash and Shampoo',
UPC: '0799457786215',
imageURL: 'https://www.cetaphil.com/us/sites/g/files/jcdfhc581/files/styles/cp_product_medium/public/09%20-%20Cetaphil%20Baby%20Wash%20_%20Shampoo%20Calendula%20-%20FRONT.jpg?itok=9ih1q8aC',
ingredients: 'Sodium Laureth Sulfate, Disodium Laureth Sulfosuccinate, Cocamidopropyl Betaine, Glycerin, Panthenol (Vitamin B5), PEG-120 Methyl Glucose Dioleate, Glycol Distearate, Hydrolyzed Wheat Protein, Calendula Officinalis Flower Extract, Aloe Barbadensis Leaf Juice Powder, Fragrance, Citric Acid, Sodium Benzoate, Phenoxyethanol, Sodium Citrate, Laureth-4, Heliotropine, Polyquaternium-10, Sodium Chloride, Sodium Hydroxide, Tocopherol (Vitamin E)'},
{name: 'Mustela Gentle Baby Shampoo and Detangler - 6.76 fl oz',
UPC: '3504108030503',
imageURL: 'https://target.scene7.com/is/image/Target/GUEST_405c0536-5d71-4cdc-9885-ff2caf56f7e8?fmt=webp&wid=1400&qlt=80',
ingredients: 'Water, Glycerin, Cocamidopropyl Betaine, Sodium Myreth Sulfate, Coco-Glucoside, Glyceryl Caprylate, Peg-150 Distearate, Parfum (Fragrance), Polyquaternium-10, Panthenol, Citric Acid, Potassium Sorbate, Butylene Glycol, Chamomilla Recutita (Matricaria) Flower Extract, Persea Gratissima (Avocado) Fruit Extract, Caramel'},
{name: 'Aveeno Baby Calming Comfort Moisturizing Lotion with Relaxing Lavender & Vanilla Scents, Non-Greasy Body Lotion with Natural Oatmeal & Dimethicone, Paraben- & Phthalate-Free, 18 fl. Oz',
UPC: '0381371162628',
imageURL: 'https://www.aveeno.com/sites/aveeno_us_2/files/product-images/ave_381371162628_baby_calming_comfort_lotion_18oz_00000_copy-min.png',
ingredients: 'Water, Glycerin, Distearyldimonium Chloride, Petrolatum, Isopropyl Palmitate, Cetyl Alcohol, Avena Sativa (Oat) Kernel Flour, Benzyl Alcohol, Fragrance, Sodium Chloride'}, 
{name: 'Noodle & Boo Bouncing Baby Bubbles for Sensitive Skin',
UPC: '0899646000884',
imageURL: 'https://images-na.ssl-images-amazon.com/images/I/61X5zdSvlKL._SL1500_.jpg',
ingredients: 'Water, Cocamidopropyl Hydroxy-Sultaine, Decyl Glucoside, PEG-150 Distearate, Disodium Laureth Sulfosuccinate, Glycerin, Polysorbate 20, Hydrolyzed Casein, Phenoxyethanol, Citric Acid, Disodium EDTA, Ethylhexylglycerin, Sodium Dehydroacetate, Fragrance (Parfum)'},
{name: 'Sesame Street Extra Gentle Bubble Bath Fragrance and Dye Free 24 Oz',
// UPC: '0735303280315',
UPC: '0012044038918',
imageURL: 'https://images-na.ssl-images-amazon.com/images/I/71bhSb7WE5L._SL1500_.jpg',
ingredients: 'Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Chloride, PEG-80, Sorbitan Laurate, Aloe Barbadensis Leaf Juice, Tocopheryl Acetate, PEG-150 Distearate, Citric Acid, Tetrasodium EDTA, Ethylhexylglycerin, Sodium Benzoate, Phenoxyethanol, Fragrance'},
{name: 'Aquaphor Baby Wash and Shampoo - Mild, Tear-Free 2-in-1 Solution for Babys Sensitive Skin',
UPC: '0072140021092',
imageURL: 'https://www.aquaphorus.com/wp-content/uploads/2016/08/AQU_Baby-WS_500mL_v3.jpg',
ingredients: 'Water, Decyl Glucoside, Sodium Myreth Sulfate, PEG-200 Hydrogenated Glyceryl Palmate, Cocamidopropyl Betaine, Panthenol, Bisabolol, Polyquaternium-10, Sea Salt, Citric Acid, Sodium Chloride, Sodium Benzoate'}, 
{name: 'Eucerin Baby Body Lotion - Hypoallergenic & Fragrance Free, Safe for Everyday Use on Sensitive Skin',
UPC: '072140003043',
imageURL: 'https://i5.walmartimages.com/asr/dbada101-3b97-425f-98d2-8971c8fdac4f.912915e181cf4718522f19ce2dfdba5d.jpeg?odnWidth=undefined&odnHeight=undefined&odnBg=ffffff',
ingredients: 'Water, Cetyl Palmitate, Glycerin, Mineral Oil, Cetyl Alcohol, Polybutene, Sorbitan Stearate, Tapioca Starch, Panthenol, Butyrospermum Parkii (Shea) Butter, Dimethicone, Phenoxyethanol, Carbomer, Pentylene Glycol, Caprylyl Glycol, Sodium Hydroxide, Sodium Citrate, Citric Acid'}, 
{name: 'Pampers Expressions Baby Wipes, Fresh Bloom Scented',
UPC: '037000507123',
imageURL: 'https://images-na.ssl-images-amazon.com/images/I/71UFY08LyVL._AC_SL1500_.jpg',
ingredients: 'Water, Citric Acid, Peg-40 Hydrogenated Castor Oil, Sodium Citrate, Sorbitan Caprylate, Sodium Benzoate, Disodium Edta, Bis-Peg/Ppg-16/16 Peg/Ppg-16/16 Dimethicone, Caprylic/Capric Triglyceride, Xanthan Gum, Fragrance/Parfum'}, 
{name: 'Tom\'s of Maine Natural Children\'s Fluoride Toothpaste, Silly Strawberry',
UPC: '035000978684',
imageURL: 'https://www.tomsofmaine.com/content/dam/cp-sites/toms/toms-of-maine/global/products/oral-care/toms-of-maine-childrens-toothpaste-silly-strawberry.png',
ingredients: 'Glycerin, Water, Calcium Carbonate, Hydrated Silica, Sodium Lauryl Sulfate, Carrageenan, Benzyl Alcohol, Natural Flavor, Citrus Limon (Lemon) Juice, Magnifera Indica (Mango) Juice, Citrus Aurantium Dulcis (Orange) Juice, Ananas Sativus (Pineapple) Fruit Juice, Fragaria Ananassa (Strawberry) Fruit Juice'}, 
{name: 'The Honest Company Perfectly Gentle Sweet Orange Vanilla Shampoo + Body Wash, Tear-Free Baby Shampoo with Naturally Derived Ingredients, Sulfate- & Paraben-Free Baby Bath',
UPC: '0816645021900',
imageURL: 'https://images-na.ssl-images-amazon.com/images/I/71QvN9SvwCL._AC_SL1500_.jpg',
ingredients: 'Water (Aqua), Aloe Barbadensis Leaf Juice, Cocamidopropyl Hydroxysultaine, Sodium Laurylglucosides Hydroxypropylsulfonate, Disodium Cocoyl Glutamate, Sodium Chloride, Sodium Cocoyl Isethionate, Chamomilla Recutita (Matricaria) Flower Extract, Camellia Sinensis Leaf Extract, Cocos Nucifera (Coconut) Fruit Extract, Citrus Aurantium Dulcis (Orange) Peel Extract, Citrus Tangerina (Tangerine) Peel Extract, Vanilla Planifolia Fruit Extract, Glycerin, Caprylyl Glycol, Panthenol, Guar Hydroxypropyltrimonium Chloride, Caprylhydroxamic Acid, Triethyl Citrate, Trisodium Ethylenediamine Disuccinate, Sodium Benzoate, Sodium PCA, Coconut Acid, Glutamic Acid, Citric Acid, Limonene'}, 
{name: 'Baby Bum Bubble Bath | Tear Free Foaming Bubble Bath for Sensitive Skin with White Ginger| Natural Fragrance | Gluten Free and Vegan',
UPC: '871760004870',
// UPC: '0012044038918',
imageURL: 'https://images-na.ssl-images-amazon.com/images/I/61A52yqFrmL._SL1500_.jpg',
ingredients: 'Water, Coco-Glucoside, Glycerin, Disodium Cocoamphodiacetate, Cocamidopropyl Hydroxysultaine, Decyl Glucoside, Glyceryl Oleate, Aloe Barbadensis Leaf Juice, Cucumis Sativus (Cucumber) Fruit Extract, Musa Sapientum (Banana) Fruit Extract, Hedychium Coronarium Root Extract, Gardenia Taitensis Flower Extract, Cocos Nucifera (Coconut) Oil, Sea Salt, Dicaprylyl Ether , Xanthan Gum, Citric Acid, Glyceryl Caprylate, Glyceryl Undecylenate, Sodium Phytate, Sodium Benzoate'}]


export const ingredientList = [ 'Sodium Laureth Sulfate', 'SLS', 'PEG', 'xynol', 'ceteareth', 'oleth', 'Benzophenone', 'Oxybenzone', 'Sulisobenzone', 'Sulisobenzone Sodium', 'BP', 'BHA', 'BHT', 'Butylated Hydroxytoluene', 'Butylated Hydroxyanisole', 'Formaldehyde', 'Quaternium-15', 'Diazolidinyl Urea', 'Imidazolidinyl Urea', 'DMDM Hydantoin', '2-Bromo-2-Nitropropane-1','3 Diol', 'Phenacetin', 'Coal Tar', 'Benzene', 'Mineral Oil', 'Ethylene Oxide', 'Chromium', 'Cadmium', 'Arsenic', 'Crystalline Silica', 'Triethanolamine', 'Diethanolamine', 'DEA', 'TEA', 'Cocamide DEA', 'Cocamide MEA', 'DEA-cetyl Phosphate', 'DEA Oleth-3 Phosphate', 'Lauramide DEA', 'Linoleamide MEA', 'Myristamide DEA', 'Oleamide DEA', 'Stearamide MEA', 'TEA-Lauryl Sulfate','PPG', 'PEG', 'Polysorbate', 'laureth', 'steareth', 'ceteareth', 'Polyoxymethylene Urea', 'Sodium Hydroxymethylglycinate', 'Bromopol','Glyoxal', 'Homosalate', 'Homomenthyl salicylate', 'HMS', 'HS', '3,3,5-Trimethyl-Cyclohexyl-Salicylate', 'Lead Acetate', 'Thimerosal', 'Hydrogenated Cotton Seed Oil', 'Sodium Hexametaphosphate', 'Fragrance', 'Parfum']